### ISSUE TITLE
updateTriggers lack explanation (Building a Graph Vis - 1. Graph Render)

### ISSUE THREAD

**Issue by themmes** [uber-common/vis-academy#47]
The final code overview of the first chapter of this tutorial includes `updateTriggers`. I am not sure where these come from, what they do or whether they are part of chapters to come.

**Comment by javidhsueh** [comment]
Hi @themmes I think you're talking about the `4. Add Color Update Trigger` in [Step4. ](http://vis.academy/#/graph-vis/4-interacting-with-graph), right?
The update trigger has been mentioned in [Step3](http://vis.academy/#/graph-vis/3-plugin-layout-engine), `4. Position Update Trigger`:

> deck.gl doesn't recalculate positions unless the data prop changes by shallow comparison. To inform deck.gl to re-evaluate getPosition outcome, we need to explicitly define updateTriggers

For more information, please check the explanation at [here](http://uber.github.io/deck.gl/#/documentation/advanced-topics/updates?section=update-triggers)

**Comment by themmes** [comment]
Thanks for pointing out! I guess I'll have to go through a bit more documentation to get my implementation to work.
