### ISSUE TITLE
add triggers to GraphRender (Building a Graph Vis - 3. Plugin Layout Engine)

### ISSUE THREAD

**Issue by themmes** [uber-common/vis-academy#48]
In step `4. Position Update Trigger` of this chapter is stated that the triggers should be added to the `LayoutEngine.js` while the example shows the code is added to functions of the `GraphRender.js`.

**Comment by javidhsueh** [comment]
Hi @themmes I'm not sure what do you mean here. The original context is:

> The layout engine has an attribute alpha represents the momentum of the current force layout simulation. Since the value of alpha changes on every simulation, we can use it as the update trigger for getPosition

The `LayoutEngine` will provide the accessor for returning the `alpha`  value and use it as the position update trigger in `GraphRender`. 

Please let me know if you still have more questions.

**Comment by themmes** [comment]
The thing is, in the code snippet listed it says:

```
// layout-engine.js
export default class GraphRender extends PureComponent {
  // ...

  renderNodeLayer() {
    return new ScatterplotLayer({
```

Note the `layout-engine.js`, while in fact the triggers are added to GraphRender in `graph-render.js`

**Comment by themmes** [comment]
But in the `graph-render.js` these functions are called `createNodeLayer()` and not `renderNodeLayer()`

As said in another issue, or I am not really getting the tutorial, or the code snippets within the tutorial are inconsistent with the final codebase on GitHub.

**Comment by javidhsueh** [comment]
Thanks for pointing out those defects. Now I realize the inconsistency between the code snippets and the final code. Will fix it soon!

**Comment by javidhsueh** [comment]
Fixed.
