### ISSUE TITLE
3D Hex rendering 'upside down'

### ISSUE THREAD

**Issue by thomasgwatson** [uber-common/vis-academy#58]
While the demo app at the top of [More Data Overlays - Hexagon](http://vis.academy/#/building-a-geospatial-app/3-more-data-overlays-hexagons) is fine, my localhost version isn't rendering correctly. The base of small hexagonal prisms are being rendered over the taller hexagonal prisms

[rendering image](https://i.imgur.com/S657k90.png)

Is there some attribute/setting that I have to flip? Some ordering of the classification ranges?

No errors are being thrown beyond a warning:
`log.js:52 luma.gl: luma.gl: `data` is deprecated and will be removed in a later version. Use `pixels` instead`

**Comment by ibgreen** [comment]
@thomasgwatson At a guess the missing piece is enabling the 3D depth testing (the "z buffer"). 

See this line: https://github.com/uber-common/vis-academy/blob/master/src/demos/building-a-geospatial-app/3-hexagon-overlay/src/deckgl-overlay.js#L29

**Comment by thomasgwatson** [comment]
Thanks for the pointer: lead me to see I'd miscalled that function

Wrong code:
`onWebGLInitialized={this.initialize}/>`
