### ISSUE TITLE
Allocation failed - process out of memory

### ISSUE THREAD

**Issue by jrfarrer** [uber-common/vis-academy#70]
I have successfully run the embedded app `3-load-config` using a different datasets and config files. However, above files sizes of 50mb, I receive the error `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory` when running `npm run start`. I have attempted to add `--max-old-space-size=2048` flags to the `npm run start` command without success. The dataset loads easily on the kepler.gl demo page. 

What configuration do I need to change for larger file sizes to work (50-250mb)?

**Comment by jckr** [comment]
@macrigiuseppe @heshan0131 can you take a look?

**Comment by macrigiuseppe** [comment]
Hi @jrfarrer,
what kind of file are you trying to use? csv, json,...?

If you could share the file it wourld be great otherwise i will try something similar.

Thank you

**Comment by jrfarrer** [comment]
Hi @macrigiuseppe - it's a csv that I wrapped in "export default `" and "`" to match the demo `nyc-trips.csv.js`. The file works at 250k records but not at 500k records. The difference in file size is 25mb vs 50mb.

**Comment by jrfarrer** [comment]
I was able to figure out a solution. In `package.json,` I changed the `webpack-dev-server` in start to `node --max-old-space-size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js`.
